### ISSUE TITLE
CRC Address setting

### ISSUE THREAD

**Issue by rhzg** [MSG134/IVCT_Compositions#12]
When starting the ivct composition without a explicit PITCH_CRCADDRESS assignment, the CRC address is set to `CRC` in the LRC settings file inside the tc-runner container. As a consequence, the SETTINGS_DESIGNATOR given in the SuT configuration is being ignored. 

The overwriting is done, because in the `prti1516eLRC.Settings` file, the LRC.overrideCrcAddressFlag is set to true. I tried to use the settings on my host (by setting ${LRC_SETTINGSDIR}:/root/prti1516e), but whenever the ivct composition is started, own settings are overwritten with some defaults (I guess defined within the LRC image).

**Comment by rhzg** [comment]
A solution to that issue is, to use the additional setting PITCH_CRCADDRESS=${DOCKERHOST} in the tc-runner service definition (if the rti is running on the same host of course). But I guess this is kind of a workaround - or is this intended?

**Comment by bergtwvd** [comment]
I do not understand why the SETTINGS_DESIGNATOR is ignored (I assume this concerns HW).

When you use the IVCT Runner image without specifying `PITCH_CRCADDRESS` then:
- The default setting for crcAddress in the LRCsettings file is `crc:8989`.
- If an LSD value (i.e. `crcAddress=somehost:8989`) is provided via the IVCT UI then this overrides whatever is set in the LRC settings file.

I assume that the IVCT passes the LSD value on to the RTI connect call ....?

Note that under the hood the LRC settings file is located in the TC Runner image under `${LRC_HOME}/code`. When the container starts, the LRC launch script (init.sh) will copy this file to `/root/prti1516e/prti1516eLRC.settings`, since this is the location where the Pitch RTI expects the file (see https://github.com/hlacontainers/lrc/blob/master/docker/context/pitch/init.sh).

You can mount your own LRC settings file by:
- setting the EV `PITCH_LRC_SETTINGS_FILE` to `/root/prti1516e/prti1516eLRC.settings`
- mount `yourSettingsFile` to `/root/prti1516e/prti1516eLRC.settings`

**Comment by rhzg** [comment]
The problem is with the runner and there are actually 2 prti1516eLRC.settings files. One is ${LRC_HOME)}/code, the other is in /root/prti1516e. Not sure which one is used, but in both there is the statement `LRC.overrideCrcAddressFlag=true`

I believe that causes the LRC lib to ignore whatever comes from the runner (which is the settings designater property of the SuT).

**Comment by bergtwvd** [comment]
The LRC settings file under $LRC_HOME/code comes straight from the pRti installer. No adaptations haven been done. Will check.

The LRC settings file is put under $LRC_HOME/code in order to have all LRC files in one folder and docker volume. Upon container launch the file is copied to the folder that the pRTI expects. This folder is under /root, outside the volume. This is different per RTI vendor.

**Comment by bergtwvd** [comment]
When I check my LRC image for 5_5_0_0 I get the output below.

The IVCT is built off the skeleton LRC image and the LRC settings file is mounted from the RTI installation directory. So `LRC.overrideCrcAddressFlag=true` can only come from your own RTI installation directory. Please check.

````
bergtwvd@PC-20915:~$ docker run -it --rm --entrypoint=sh hlacontainers/lrc:pitch-5_5_0_0-alpine -c "cat /usr/local/lrc/code/prti1516eLRC.settings" | grep override
LRC.hla13.overrideTime=false
LRC.hla1516.overrideTime=false
LRC.overrideCrcAddressFlag=false
LRC.overrideFederateNameFlag=false
LRC.overrideFederateName=
LRC.overrideFederateTypeFlag=false
LRC.overrideFederateType=
LRC.overrideFederationNameFlag=false
LRC.overrideFederationName=
LRC.overrideFederationTimeTypeFlag=false
LRC.overrideFederationTimeType=
LRC.overrideFomAtCreateFlag=false
LRC.overrideFomAtCreate=
LRC.overrideFomAtJoinFlag=false
LRC.overrideFomAtJoin=
bergtwvd@PC-20915:~$
````

**Comment by rhzg** [comment]
I guess you must be right. With my current setup I can not replicate this effect. Maybe I was confused by the fact, that multiple prti federates on the same machine are sharing their settings. I'll close that issue, thanks for your help.
